<?php
///**
// * Created by PhpStorm.
// * User: walmirlsj
// * Date: 08/07/15
// * Time: 20:55
// */
//
//
//<!--                        <div class="form-group">-->
//                        <!--                            <label for="file" class="col-lg-4 col-md-4 control-label">-->
//                        <!--                                Enviar fotos-->
//                        <!--                            </label>-->
//                        <!---->
//                        <!--                            <div class="col-lg-5 col-md-5">-->
//                        <!--                                <fieldset>-->
//                        <!--                                    <!--                        <legend>Upload new files</legend>-->-->
//                        <!--<!--                                    <form name="uploadFiles" id="uploadFiles" style='clearfix' method="post"-->-->
//                        <!--<!--                                          action="/catalogo/teste/upload" enctype="multipart/form-data">-->-->
//                        <!--                                        <button type="submit" class="btn btn-primary pull-right">Upload files</button>-->
//                        <!--                                        <input type="file" name="files[]" class="filestyle" data-buttonBefore="true"-->
//                        <!--                                               data-buttonText="Procurar Arquivo"-->
//                        <!--                                               multiple="multiple">-->
//                        <!---->
//                        <!--<!--                                    </form>-->-->
//                        <!--                                </fieldset>-->
//                        <!--                            </div>-->
//                        <!--                        </div>-->