index2.phtml<?php
/**
 * Created by PhpStorm.
 * User: walmirlsj
 * Date: 05/07/15
 * Time: 22:42
 */

if (count($this->messages["Danger"]) or count($this->messages["Warning"]) or count($this->messages["Success"]) or count($this->messages["Messages"])) {
    ?>
    <div class="col-lg-2" Style="position: fixed; top:50px; right: 0; z-index: 500;">
        <?php $id = 0; ?>
        <?php foreach ($this->messages as $alert => $type) { ?>
            <?php foreach ($type as $pox => $msg) { ?>
                <div id="<?php echo 'alert_id' . $id; ?>"
                     class="alert alert-block <?php echo strtolower('alert-' . $alert) ?>">
                    <a class="close" data-dismiss="alert" href="#">x</a>

                    <p><?php echo $this->translate($msg) ?></p>
                </div>

                <script>
                    setTimeout(function () {
                        $('<?php echo "#alert_id".$id; ?>').fadeOut(1500);
                    }, 3000);
                </script>
                <?php $id++; ?>
            <?php } ?>
        <?php } ?>
    </div>


<?php }//else: ?>

<div class="row-fluid">
    <div class="panel panel-primary panel-crud-dark">
        <div class="panel-heading clearfix">
            <span class="panel-title pull-left input-sm">
                <b><i class="glyphicon glyphicon-list"></i> <?php echo $this->translate('Categorias') ?></b>
            </span>

            <div class="row-fluid">
                <div class="col-lg-5 pull-right clearfix" style="padding-left:0;">
                    <?php
                    //                    var_dump($this->frm_search['limit']);
                    $limit = $this->frm_search['limit'];
                    //                    echo $limit;
                    ?>
                    <form id='frmSearch' class="form-query no-padding" role="form" method="get"
                          action="<?php echo $_SERVER["REQUEST_URI"];
                          //echo $this->url('catalogo/default',
                          //array('controller' => 'categoria', 'action' => 'index')); ?>">

                        <a data-toggle="modal" href="<?php echo $this->url('catalogo/default',
                            array('controller' => 'categoria', 'action' => 'inserir')); //#ModalNew ?>"
                           class="btn btn-primary pull-left action"
                           title="<?php echo $this->translate('Novo') ?>"
                           style="margin-right: 5px;">
                            <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo') ?>
                        </a>

                        <div class="input-group">
                            <?php
                            $search = $this->frm_search['search'];
                            $type = $this->frm_search['type'];
                            $limit = $this->frm_search['limit'];
                            ?>
                            <input id="search" name="search" required="true" type="text"
                                   class="form-control" <?php echo ($search != null) ? 'value="' . $search . '"' : ''; ?>>
                            <span class="input-group-btn">
                                <select id="type" name="type" required="true" class='form-control'
                                        style="width: 100px;">
                                    <option value=""
                                        <?php echo (null === $type) ? 'selected' : ''; ?>>
                                        --- Selecione ---
                                    </option>
                                    <option value="1"
                                        <?php echo ($type === 1) ? 'selected' : ''; ?>>Descricão
                                    </option>
                                    <option value="2"
                                        <?php echo ($type === 2) ? 'selected' : ''; ?>>Secção
                                    </option>
                                    <option value="3"
                                        <?php echo ($type === 3) ? 'selected' : ''; ?>>Adicionado em
                                    </option>
                                    <option value="4"
                                        <?php echo ($type === 4) ? 'selected' : ''; ?>>Atualizado
                                    </option>
                                </select>
                                <script>
                                    $('#type').change(function (e) {
//                            alert('executei');
                                        var obj = $('#search');
//                                        alert(eval(this.value));
                                        switch (eval(this.value)) {
                                            case 1://Data
                                                obj.attr('type', 'text');
                                                obj.attr('placeholder', '');
                                                break;
                                            case 2: //Profissional
                                                obj.attr('type', 'text');
                                                obj.attr('placeholder', '');
                                                break;
                                            case 3://Teste
                                                obj.attr('type', 'date');
                                                obj.attr('placeholder', '');
                                                break;
                                            case 4://Duracao
                                                obj.attr('type', 'date');
                                                obj.attr('placeholder', '');
                                                break;
                                            default:
                                                obj.attr('type', 'text');
                                                obj.attr('placeholder', 'Pesquise aqui');
                                        }
                                    }).change();
                                </script>
                            </span>
                                <span class="input-group-btn">
                                    <button id="btnSearch" class="btn btn-info form-control" type="submit"><i
                                            class="glyphicon glyphicon-search"></i>
                                    </button>
                                </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="panel-body no-padding clearfix" style="margin: 0;padding: 0;">
            <div class="table-responsive">
                <table class="table table-bordered" style="margin: 0;">
                    <thead>
                    <tr>
                        <th class="col-lg-1">#</th>
                        <th class="col-lg-4">Descricão</th>
                        <th class="col-lg-4">Secção</th>
                        <th class="col-lg-1">Adicionado</th>
                        <th class="col-lg-1">Atualizado</th>
                        <th class="col-lg-1">Ação</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 0; ?>
                    <?php foreach ($this->data as $entity): ?>
                        <?php $i++; ?>
                        <tr>
                            <td>
                                <?php echo $entity->getId(); ?>
                            </td>
                            <td>
                                <?php echo $entity->getDescricao(); ?>
                            </td>
                            <td>
                                <?php echo $entity->getSeccao(); ?>
                            </td>

                            <td>
                                <?php echo ($entity->getCreatedAt()) ? $entity->getCreatedAt()->format('d/m/Y') : "--/--/--"; ?>
                            </td>

                            <td>
                                <?php echo ($entity->getUpdatedAt()) ? $entity->getUpdatedAt()->format('d/m/Y') : "--/--/--"; ?>
                            </td>

                            <td style="padding: 0 !important; text-align: center;">
                                <a class="btn btn-sm btn-primary col-lg-6 action"

                                   href="<?php echo $this->url('catalogo/default',
                                       array('controller' => 'categoria', 'action' => 'editar', 'refid' => $entity->getId())); ?>">
                                    <i class="glyphicon glyphicon-pencil text-primary"
                                       style="font-weight: bold;color: white;">

                                    </i>
                                </a>

                                <a class="btn btn-sm btn-danger col-xs-6" data-toggle="confirm"
                                   href="<?php echo $this->url('catalogo/default',
                                       array('controller' => 'categoria', 'action' => 'remover', 'refid' => $entity->getId())); ?>">
                                    <i
                                        class="glyphicon glyphicon-trash text-danger"
                                        style="font-weight: bold;color: white;"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                    <?php for (; $i < 10; $i++) { ?>
                        <tr class="text-center">
                            <td style="padding: 15px !important;"></td>
                            <td style="padding: 15px !important;"></td>
                            <td style="padding: 15px !important;"></td>
                            <td style="padding: 15px !important;"></td>
                            <td style="padding: 15px !important;"></td>
                            <td style="padding: 15px !important;"></td>
                        </tr>
                    <?php }; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <script>
            $("[data-toggle=confirm]").click(function () {
                $(this).click.url = $(this).attr('href');
            }).confirm({
                text: "Deseja realmente deletar?",
                title: "Confirmar",
                confirm: function (button) {
                    $(location).attr('href', $(this).click.url);
//                    $(this).trigger('click');
                },
                cancel: function (button) {
                    e.preventDefault();
                },
                confirmButton: "Sim",
                cancelButton: "Não"
            });
        </script>

        <div class="panel-footer">
            <div class="row">
                <div class="col-md-4">
                    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'search')); ?>
                </div>
                <div class="pull-right">
                    <form class="form-query form-group" id="frmSearch2"
                          action="<?php echo strtok($_SERVER["REQUEST_URI"], '?'); ?>">
                        <select id="limit" name="limit">
                            <option value="10" <?php echo ($limit === 10) ? 'selected' : ''; ?>>10</option>
                            <option value="20" <?php echo ($limit === 20) ? 'selected' : ''; ?>>20</option>
                            <option value="30" <?php echo ($limit === 30) ? 'selected' : ''; ?>>30</option>
                            <option value="50" <?php echo ($limit === 50) ? 'selected' : ''; ?>>50</option>
                            <option value="100" <?php echo ($limit === 100) ? 'selected' : ''; ?>>100</option>
                        </select>
                        <input class="submit" type="submit"/>
                    </form>

                    <script>
                        $("document").ready(function () {
                            /* attach a submit handler to the form */
                            $(".form-query").submit(function (e) {
                                e.preventDefault();
                                e.stopPropagation();
                                /* get some values from elements on the page: */
//                            var val = $(this).serialize();
//                            var url = $(this).attr('action');//;
//                                alert(val+' ---');

                                var query = $('#frmSearch').serialize();
                                var limit = $('#frmSearch2').serialize();
//                            alert(query + '&' + limit);
                                dados = query + '&' + limit;
//                                alert($(this).action);
//                                dados = dados.replace(/=/g, "/");
//                                dados = dados.replace(/&/g, "/");
//                                url = $(this).attr('action');

                                urlPattern = '<?php echo $urlPattern = strtok($_SERVER["REQUEST_URI"],'?');?>';
//                            urlPattern = '<?php //echo $urlPattern = strtok($_SERVER["REQUEST_URI"], '?');?>//';
                                //echo $_SERVER   ["REQUEST_URI"]; ?>';
                                <!--                                -->
                                <?php //echo $this->url('catalogo/default',
                                //                                array('controller' => 'categoria')); ?>
//                            alert('ok');
                                url = urlPattern + '?' + dados;
//                                alert(url);
                                $(location).attr('href', url);

                                e.preventDefault();
                            });
                        });
                    </script>
                </div>
            </div>
        </div>

    </div>
</div>
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery.confirm.js');
?>

<div id="result"></div>
<script>


    //        $("document").ready(function () {
    //            $(function () {
    //                /* attach a submit handler to the form */
    //                $(".panel-action-form").submit(function (event) {
    //
    //                /* stop form from submitting normally */
    //                event.preventDefault();
    //                event.stopPropagation();
    //
    //                /*clear result div*/
    //                $("#result").html('');
    //
    //                /* get some values from elements on the page: */
    //                var val = $(this).serialize();
    //                //var url = $(this).action;
    //                /* Send the data using post and put the results in a div */
    //                $.ajax({
    //                    url: url,
    //                    type: "post",
    //                    data: val,
    //                    datatype: 'json',
    //                    success: function (data) {
    //                        $('#result').html(
    //                            '<div class="panel-info-log col-lg-2" Style="position: fixed; top:50px; right: 0; z-index: 500;">' +
    //                            '<div class="alert alert-block">' +
    //                            '<a class="close" data-dismiss="alert" href="#">x</a>' +
    //                            data.status + ':' + data.message +
    //                            '</div>' +
    //                            '</div>'
    //                        );
    //                        $("#result").addClass('msg_notice');
    //                        $("#result").fadeIn(1500);
    //                    },
    //                    error: function () {
    //                        $("#result").html('There was an error updating the settings');
    //                        $("#result").addClass('msg_error');
    //                        $("#result").fadeIn(1500);
    //                    }
    //                });
    //            });
    ////        })
    //    });
</script>