<?php
//
//$entity = $this->entity;
////
////if($this->entity===null)
////    echo 'null';
////else
////    echo 'ok';
//
//if (NULL !== $this->entity) {
//    ?>
<!--    <div class="col-lg-12">-->
<!---->
<!--        <div class="panel panel-crud-dark">-->
<!--                        <div class="panel-heading">-->
<!--                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--                                <span aria-hidden="true">&times;</span>-->
<!--                                </button>-->
<!--                                <span class="h3">Sobre o veiculo</span>-->
<!--                        </div>-->
<!--                        <div class="panel-body text-left">-->
<!--                            <dl>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Marca: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getMarca()->getDescricao(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Modelo: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getModelo(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Versão: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getVersao(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Ano/modelo: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getAnoModelo() ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Cor: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getCor(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Km: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getKm(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Portas: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getPortas(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Direção: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getDirecao(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Transmissão: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getTransmissao(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Opcionais: </span><span-->
<!--                                        class="value">--><?php //echo $entity->getOpcionais(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Observação: </span><span class="value">-->
<!--                                        --><?php //echo $entity->getObs(); ?>
<!--                                    </span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Preço: R$ </span><span-->
<!--                                        class="value">--><?php //echo $entity->getPrice(); ?><!--</span>-->
<!--                                </dd>-->
<!--                                <dd>-->
<!--                                    <span class="legend">Vendido? </span><span-->
<!--                                        class="value">--><?php //echo $entity->isStocked() ? 'Sim' : 'Não'; ?><!--</span>-->
<!--                                </dd>-->
<!--                            </dl>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!---->
<!---->
<?php //} else { ?>
<!---->
<!--    <div class="jumbotron">-->
<!--        <h1>Ops.!</h1>-->
<!---->
<!--        <p>Veiculo não encontrado.</p>-->
<!--        <!--        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>-->-->
<!--    </div>-->
<!---->
<?php //} ?>