
<div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <span class="panel-title">Novo usuário</span>
            </div>
            <div class="panel-body">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('user/default', array('controller' => 'manager', 'action' => 'inserir')));
                //    $form->setAttribute('class','row');
                $form->prepare();

                echo $this->form()->openTag($form);
                //                echo $this->formCollection($form);
                ?>
                <div class="form-group col-xs-12">
                    <?php echo $this->formLabel($form->get('login')->setAttribute("class", "col-xs-12 control-label")) ?>
                    <?php echo $this->formElement($form->get('login')->setAttribute("class", "form-control col-xs-12")) ?>
                    <?php echo $this->formElementErrors($form->get('login')->setAttribute("class", "text-danger")) ?>

                    <?php //echo $this->formRow($form->get('login')); ?>
                    <?php //echo $this->formlabel($form->get('id')); ?>
                    <?php //echo $this->formElementErrors($form->get('id')) ?>
                    <?php //echo $this->formElement($form->get('id')); ?>
                </div>
                <div class="form-group col-xs-12">
                    <?php echo $this->formLabel($form->get('email')->setAttribute("class", "col-xs-12 control-label")) ?>
                    <?php echo $this->formElement($form->get('email')->setAttribute("class", "form-control col-xs-12")) ?>
                    <?php echo $this->formElementErrors($form->get('email')->setAttribute("class", "text-danger")) ?>

                    <?php //echo $this->formRow($form->get('email')); ?>
                </div>
                <div class="form-group col-xs-12">
                    <?php echo $this->formLabel($form->get('password')->setAttribute("class", "col-xs-12 control-label")) ?>
                    <?php echo $this->formElement($form->get('password')->setAttribute("class", "form-control col-xs-12")) ?>
                    <?php echo $this->formElementErrors($form->get('password')->setAttribute("class", "text-danger")) ?>
                    <?php //echo $this->formRow($form->get('password')); ?>
                </div>
                <div class="form-group col-xs-12">
                    <?php echo $this->formLabel($form->get('confirmation')->setAttribute("class", "col-xs-12 control-label")) ?>
                    <?php echo $this->formElement($form->get('confirmation')->setAttribute("class", "form-control col-xs-12")) ?>
                    <?php echo $this->formElementErrors($form->get('confirmation')->setAttribute("class", "text-danger")) ?>
                    <?php //echo $this->formRow($form->get('confirmation')); ?>
                </div>
<!--                <div class="form-group col-xs-12">-->
<!--                    --><?php //echo $this->formLabel($form->get('role')->setAttribute("class", "col-xs-12 control-label")) ?>
<!--                    --><?php //echo $this->formElement($form->get('role')->setAttribute("class", "form-control col-xs-12")) ?>
<!--                    --><?php //echo $this->formElementErrors($form->get('role')) ?>
<!--                    --><?php ////echo $this->formRow($form->get('tipo')); ?>
<!--                </div>-->
                <div class="form-group col-xs-12">
                    <?php echo $this->formLabel($form->get('captcha')->setAttribute("class", "col-xs-12 control-label")) ?>
                    <?php echo $this->formElement($form->get('captcha')->setAttribute("class", "form-control col-xs-12")) ?>
                    <?php echo $this->formElementErrors($form->get('captcha')) ?>
                    <?php //echo $this->formRow($form->get('tipo')); ?>
                </div>

                <div class="form-group col-xs-12">
                    <?php //echo $this->formElement($form->get('submit')->setAttribute("class", "form-control col-xs-12")) ?>
                    <?php //echo $this->formElementErrors($form->get('submit')->setAttribute("class", "text-danger")) ?>
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
                <div class="form-group col-xs-12 text-danger">
                    <?php echo $this->formRow($form->get('security')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>


        </div>
    </div>
</div>