<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user-recover'))
    ->setAttribute("class", "form-login");
$form->prepare();

echo $this->form()->openTag($form);
?>
<fieldset class="clearfix text-left">
    <legend>Recuperar acesso a conta</legend>
    <div class="form-group ">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i>
            <?php echo $this->formElement($form->get('login')) ?>
        </div>
    </div>

    <div class="form-group clearfix">
        <?php echo $this->formElement($form->get('submit')) ?>
    </div>
    <div class="form-group pagination-centered no-padding">
<!--        <span><a href="/register">Registrar me</a> / <a href="/recover">Esqueci a senha</a></span>-->
    </div>
</fieldset>
