<?php
/**
 * Created by PhpStorm.
 * User: walmirlsj
 * Date: 02/05/14
 * Time: 22:37
 */

if (count($this->messages["Danger"]) or count($this->messages["Warning"]) or count($this->messages["Success"]) or count($this->messages["Info"]) or count($this->messages["Messages"])) {
    ?>
    <?php foreach ($this->messages as $alert => $type) { ?>
        <?php foreach ($type as $pox => $msg) { ?>
            <div class="alert alert-block <?php echo strtolower('alert-' . $alert) ?>">
                <a class="close" data-dismiss="alert" href="#">x</a>

                <p><?php echo $this->translate($msg) ?></p>
            </div>
        <?php } ?>
    <?php } ?>

<?php }//else: ?>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('cliente/default', array('controller' => 'Index', 'action' => 'inserir')));
$form->setAttribute('action', $this->url('cliente/default', array('controller' => 'manager', 'action' => 'editar')));
//    $form->setAttribute('class','form-horizontal');
$form->prepare();
?>
<div class="col-lg-12 row clearfix panel-action">
    <?php echo $this->form()->openTag($form); //    echo $this->formCollection($form);?>
    <div class="panel panel-primary panel-crud-editar">
        <div class="panel-heading">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <span class="panel-title"><i class="glyphicon glyphicon-pencil"></i> <?php echo $this->translate('Editar registro do Cliente') ?></span>
        </div>

        <div class="panel-body clearfix" style="/*font-weight:bold;*/">

            <?php foreach ($form as $element) { ?>
                <?php
                if ($element->getAttribute('type') == "submit" || $element->getAttribute('type') == "button" || $element->getAttribute('type') == "hidden")
                    continue;
                ?>
                <div class="col-lg-4 form-control-static clearfix" style="margin-bottom: 0;padding: 10px;">
                    <?php if (null != $element->getLabel()) { ?>
                        <label for="<?php echo $element->getName() ?>"
                               style="margin-bottom: 0;font-size: medium;/*color: #5E4444;*/"
                               class="label label-danger col-lg-12">
                            <?php echo $element->getLabel() ?>
                        </label>
                    <?php } ?>

                    <div class="col-lg-12 input-group">
                        <?php
                        echo $this->formElement($element);
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat('<div class="text-danger">')
                            ->setMessageSeparatorString('</div><div class="help-inline">')
                            ->setMessageCloseString('</div>')
                            ->render($element);
                        ?>
                    </div>
                </div>
            <?php } ?>

        </div>

        <div class="panel-footer clearfix" style="/*background: #00A0BB !important;*/">
            <?php foreach ($form as $element) {

                if ($element->getAttribute('type') == "hidden") {
                    echo $this->formHidden($element);
                    continue;
                } else if ($element->getAttribute('type') != "submit" && $element->getAttribute('type') != "button") {
                    continue;
                } else {
                    echo $this->formElement($element);
                }
            } ?>
        </div>

    </div>

</div>
<?php echo $this->form()->closeTag(); ?>
<?php //endif; ?>
<div class="clearfix"></div>