<?php
/**
 * Created by PhpStorm.
 * User: walmirlsj
 * Date: 05/07/15
 * Time: 22:42
 */

if (count($this->messages["Danger"]) or count($this->messages["Warning"]) or count($this->messages["Success"]) or count($this->messages["Messages"])) {
    ?>
    <?php foreach ($this->messages as $alert => $type) { ?>
        <?php foreach ($type as $pox => $msg) { ?>
            <div class="alert alert-block <?php echo strtolower('alert-' . $alert) ?>">
                <a class="close" data-dismiss="alert" href="#">x</a>

                <p><?php echo $this->translate($msg) ?></p>
            </div>
        <?php } ?>
    <?php } ?>

<?php }//else: ?>

<div class="row-fluid">
    <div class="panel panel-primary panel-crud-dark">
        <div class="panel-heading clearfix">
            <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                <!--            <span class="panel-title">-->
                <b><?php echo $this->translate('Clientes') ?></b>
                <!--                >-->
                <!--                --><?php //echo $this->translate('Resultados de Testes') ?>
                <!--        </span>-->
            </h4>

            <div class="row">
                <div class="col-xs-6 col-md-4 col-lg-4 pull-right" style="padding-left:0;">

                    <form id='frmSearch' class="no-padding" role="form" method="get"
                          action="<?php echo $this->url('catalogo/default',
                              array('controller' => 'manager', 'action' => 'index')); ?>">

                        <div class="col-md-4 no-padding-right">
                            <select id="type" name="type" required="true" class='form-control col-md-2'>
                                <!--                                <option value="1" -->
                                <?php //echo ($frm_search['type']==1)?'selected':'';?><!-->Data</option>-->
                                <!--                                <option value="2" -->
                                <?php //echo ($frm_search['type']==2)?'selected':'';?><!-->Profissional</option>-->
                                <!--                                <option value="3" -->
                                <?php //echo ($frm_search['type']==3)?'selected':'';?><!-->Teste</option>-->
                                <!--                                <option value="4" -->
                                <?php //echo ($frm_search['type']==4)?'selected':'';?><!-->Duração</option>-->
                                <!--                                <option value="5" -->
                                <?php //echo ($frm_search['type']==5)?'selected':'';?><!-->Valor</option>-->
                            </select>
                        </div>
                        <div class="input-group col-md-8">
                            <input id="search" name="search" required="true" type="date"
                                   class="form-control" <?php //echo ($frm_search['search']!=null)?'value="'.$frm_search['search'].'"':'';?>>
                                <span class="input-group-btn">
                                    <button id="btnSearch" class="btn btn-info form-control" type="submit"><i
                                            class="glyphicon glyphicon-search"></i>
                                    </button>
                                </span>
                        </div>
                    </form>
                </div>
                <!--                data-toggle="modal" href="#myModal" class="btn btn-primary"-->
                <!--                <button data-toggle="btn-actions"-->
                <!--                        class="btn btn-primary pull-right"-->
                <!--                        title="--><?php //echo $this->translate('Novo') ?><!--"-->
                <!--                        style="margin-right: 5px;"-->
                <!--                        data-toggle="modal" data-target=".bs-example-modal-lg">-->
                <!--                    <i class="glyphicon glyphicon-plus-sign"></i> --><?php //echo $this->translate('Novo') ?>
                <!--                </button>-->
                <a class="btn btn-primary pull-right action" role="button" data-toggle="modal"
                   data-target=".bs-example-modal-lg"
                   href="<?php echo $this->url('cliente/default',
                       array('controller' => 'index', 'action' => 'inserir')); ?>"><i
                        class="glyphicon glyphicon-plus-sign"></i> Novo</a>

                <!--                <a class="btn btn-primary pull-right" title="-->
                <?php //echo $this->translate('Novo') ?><!--"-->
                <!--                   style="margin-right: 5px;"-->
                <!--                   href="-->
                <?php //echo $this->url('atleta/default', array('controller' => 'result', 'action' => 'new')); ?><!--">-->
                <!--                    <i class="glyphicon glyphicon-plus-sign"></i> --><?php //echo $this->translate('Novo') ?>
                <!--                </a>-->
            </div>
        </div>

        <div class="panel-body no-padding" style="margin: 0;padding: 0;">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <!--                    <th class="text-center">#</th>-->
                        <th class="text-center col-md-3">Nome</th>
                        <th class="text-center col-md-1">RG</th>
                        <th class="text-center col-md-1">CPF</th>
                        <th class="text-center col-md-1">Telefone</th>
                        <th class="text-center col-md-1">Celular</th>
                        <th class="text-center col-md-1">Ultima Atualização</th>
                        <th class="text-center col-md-1">Ação</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 0; ?>
                    <?php foreach ($this->data as $entity): ?>
                        <?php $i++; ?>
                        <!--                        --><?php //$entity = new \Cliente\Entity\Cliente(); ?>
                        <tr class="text-center">
                            <!--                            <td>--><?php //echo ++$count;//$count++; ?><!--</td>-->
                            <?php //echo $entity->getDataNasc()->format('d/m/Y'); ?><!--</td>-->
                            <?php //echo ($entity->getProfissional()) ? $entity->getProfissional()->getNome() : "Não a vinculo"; ?><!--</td>-->
                            <!--                                -->
                            <?php //echo ($entity->getValidadoAtleta()) ? $entity->getValidadoAtleta()->format('d/m/Y') : "--/--/--"; ?><!--</td>-->
                            <td>
                                <?php echo $entity->getNome() . ' ' . $entity->getSobreNome(); ?>
                            </td>
                            <td>
                                <?php echo $entity->getRg(); ?>
                            </td>

                            <td>
                                <?php echo $entity->getCpf(); ?>
                            </td>
                            <td>
                                <?php echo $entity->getTelefone(); ?>
                            </td>
                            <td>
                                <?php echo $entity->getCelular(); ?>
                            </td>
                            <td>
                                <?php echo ($entity->getUpdatedAt()) ? $entity->getUpdatedAt()->format('d/m/Y') : "--/--/--"; ?>
                            </td>

                            <td>
                                <?php //echo $this->url('cliente/default', array('controller' => 'manager', 'action' => 'detalhe')) ?>
                                <a id="action-edit" class="btn-sm btn-primary action"
                                   href="<?php echo $this->url('cliente/default', array('controller' => 'manager', 'action' => 'detalhe',
                                       'refid' => $entity->getId())); ?>"><i
                                        class="glyphicon glyphicon-eye-open"></i></a>
                                <a id="action-edit" class="btn-sm btn-success action"
                                   href="<?php echo $this->url('cliente/default',
                                       array('controller' => 'manager', 'action' => 'editar', 'refid' => $entity->getId())); ?>"><i
                                        class="glyphicon glyphicon-edit"></i></a>
                                <a class="btn-sm btn-danger" data-toggle="confirm"
                                   href="<?php echo $this->url('cliente/default',
                                       array('controller' => 'manager', 'action' => 'remover', 'refid' => $entity->getId())); ?>"><i
                                        class="glyphicon glyphicon-trash"></i> </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <?php for (; $i < 10; $i++) { ?>
                        <tr class="text-center">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    <?php }; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="panel-footer">
            <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
        </div>

    </div>
</div>
<!--<!-- Large modal -->
<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal-->
<!--</button>-->

<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal-->

<?php
/*
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="box-actionsLabel">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="box-actionsLabel">Teste</h4>
            </div>
            <div class="modal-body">


                <?php
                echo $this->partial($this->content_temp);
//                echo $this->content_temp;
                ?>

                <?php $label = 'Teste'; ?>
                <?php echo $this->partial('partials/content_temp', array('label' => $label)); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<!--/ Delete Label Modal -->
<?php /*
<div id="modal-actions" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="box-actionsLabel"
     style="display: block;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="box-actionsLabel">Teste</h4>
            </div>
            <div class="modal-body">
                <?php $label = 'Teste'; ?>
                <?php $this->partial('partials/content_temp', array('label' => $label)) ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
*/ ?>

<script>
    // Fill modal with content from link href
    $("#btn-actions").on("show.bs.modal", function (e) {
        var link = $(e.relatedTarget);
        $(this).find(".modal-actions").load(<?php echo $this->url('catalogo/default',
                array('controller' => 'manager',
            'action' => 'index')); ?>);
    });

    //    $("#frmLogin").load('/auth');

    //    $('#box-actions').click(function (e) {
    //        e.preventDefault();
    //        e.stopPropagation();
    //        $("modal-actions").load(
    //            <?php //echo $this->url('catalogo/default',
//                array('controller' => 'manager',
//            'action' => 'index')); ?>
    //        );
    //    });
    //
    //    $("#frmLogin").load('/auth');
    //
    //    $("[data-toggle=confirm]").click(function () {
    //        $(this).click.url = $(this).attr('href');
    //    }).confirm({
    //        text: "Deseja realmente deletar?",
    //        title: "Confirmar",
    //        confirm: function (button) {
    //            $(location).attr('href', $(this).click.url);
    ////                    $(this).trigger('click');
    //        },
    //        cancel: function (button) {
    //            e.preventDefault();
    //        },
    //        confirmButton: "Sim",
    //        cancelButton: "Não"
    //    });
</script>


<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery.confirm.js');
?>
