
<div class="jumbotron"  id="div_top" align="center">
    <div id="div_top_sub" >
        <h1 align="center"><?php echo sprintf($this->translate('Bem Vindo'), '<span class="zf-green">', '</span>') ?></h1>
        <h2 align="center"><?php echo sprintf($this->translate('Gerenciador de %s Medidas Protetivas%s de Coxim - Mato Grosso Do Sul'), '<span class="zf-green">', '</span>') ?></h2>
        <h2 align="center"><?php echo sprintf($this->translate(''), '<span class="alert-info">', '</span>') ?></h2>

        <h3 align="center"><?php echo sprintf($this->translate('%s EM DESENVOLVIMENTO.%s'), '<span class="alert-danger">', '</span>') ?></h3>
        <h3 align="center"><?php echo sprintf($this->translate('Este WebSite está sendo desenvolvido com fins de estabelecer um melhor gerenciamento das medidas protetivas do %s 5ª BPM-MS %s..'), '<span class="zf-blue">', '</span>') ?></h3>
        <p  align="center"><a class="btn btn-success btn-lg" href="" target="_parent"><?php echo $this->translate('') ?> &raquo;</a></p>
        <br>
        <br>

        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Webmail') ?></h3>
            </div>
            <div class="panel-body">
                <p></bt><?php echo sprintf($this->translate('Webmail oficial do Estado de Mato Grosso do Sul'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <br><br><br><br><br>  <p><a class="btn btn-success pull-right" href="http://webmail.ms.gov.br/mail/" target="_blank"><?php echo $this->translate('Webmail') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Sigo') ?></h3>
            </div>
            <div class="panel-body">
                <p align="justify"><?php echo sprintf($this->translate('É um conjunto sistêmico que permite unificar, organizar, padronizar, agilizar ações e procedimentos, proporcionando identificação instantânea de áreas, setores, bairros, datas e horários críticos com significativa redução do tempo de ação e dos custos em toda estrutura, é uma solução completa e com eficiência. '), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://www.sigo.ms.gov.br/" target="_blank"><?php echo $this->translate('SIGO') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Infoseg') ?></h3>
            </div>
            <div class="panel-body">
                <p align="justify"><?php echo sprintf($this->translate('A Integração das Informações de Segurança Pública, Justiça e Fiscalização, conhecida como Infoseg, reúne informações de sistemas referentes a veículos, condutores e armas. Estes dados são disponibilizados ao usuário da Rede Infoseg, de acordo com o seu perfil de acesso, diretamente às bases do Sinarm, Renach e Renavam..'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://www.infoseg.gov.br/" target="_blank"><?php echo $this->translate('REDE INFOSEG - SENASP') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
