<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <span class="panel-title pull-left">
                <h4 class=""><?php echo $this->translate('Admin') ?> > <?php echo $this->translate('User') ?></h4>
            </span>

            <div class="row">
                <div class="col-xs-7 col-md-4 col-lg-4 pull-right" style="padding-left:0;">

                    <form class="no-padding" role="form">
                        <div class="input-group">
                            <input type="text" class="form-control">
                            <span class="input-group-btn">
                                <button class="btn btn-info form-control" type="submit"><i
                                        class="glyphicon glyphicon-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>
                <!--                data-toggle="modal" href="#myModal" class="btn btn-primary"-->
                <a data-toggle="modal"
                   href="<?php echo $this->url('user/default', array('controller' => 'users', 'action' => 'inserir')); ?>"
                   class="btn btn-primary pull-right"
                   title="<?php echo $this->translate('Novo') ?>"
                   style="margin-right: 5px;">
                    <i class="glyphicon glyphicon-plus-sign"></i> <?php echo $this->translate('Novo') ?>
                </a>

            </div>
        </div>
        <div class="panel-body">
            <table class="table table-responsive table-bordered no-padding">
                <tr>
                    <th>Login</th>
                    <th>Email</th>
                    <th>Tipo</th>
                    <th>Ação</th>
                </tr>

                <?php foreach ($this->data as $entity): ?>
                    <tr>
                        <td><?php echo $entity->getLogin(); ?></td>
                        <td><?php echo $entity->getEmail(); ?></td>
                        <td><?php echo $entity->getRole(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('user/default',
                                array('controller' => 'users', 'action' => 'editar', 'id' => $entity->getId()));?>"><i class="glyphicon glyphicon-edit text-success"></i></a>

                            <a href="<?php echo $this->url('user/default',
                                array('controller' => 'users', 'action' => 'remover', 'id' => $entity->getId()));?>"><i class="glyphicon glyphicon-trash text-danger"></i></a>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <div class="panel-footer">
            <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
        </div>

    </div>
</div>
