<?php
/**
 * Created by PhpStorm.
 * User: walmirlsj
 * Date: 05/07/15
 * Time: 22:42
 */

if (count($this->messages["Danger"]) or count($this->messages["Warning"]) or count($this->messages["Success"]) or count($this->messages["Messages"])) {
    ?>
    <?php foreach ($this->messages as $alert => $type) { ?>
        <?php foreach ($type as $pox => $msg) { ?>
            <div class="alert alert-block <?php echo strtolower('alert-' . $alert) ?>">
                <a class="close" data-dismiss="alert" href="#">x</a>

                <p><?php echo $this->translate($msg) ?></p>
            </div>
        <?php } ?>
    <?php } ?>

<?php }//else: ?>


<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading clearfix">
                        <span class="panel-title pull-left">
//            <h4 class="">

                                // <?php echo $this->translate('Lista de Medidas') ?>
                                <!--                >-->
                                <!--                --><?php //echo $this->translate('Privileges') ?>
                                <!--            </h4>-->
                    </span>

            <div class="row">
                <div class="col-xs-7 col-md-4 col-lg-4 pull-right" style="padding-left:0;">

                    <form class="no-padding" role="form">
                        <div class="input-group">
                            <input type="text" class="form-control">
                            <span class="input-group-btn">
                                <button class="btn btn-info form-control" type="submit"><i
                                        class="glyphicon glyphicon-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php
        $user = $this->auth->getIdentity()['user'];
        var_dump($this->auth->getIdentity()['user'])->getRole()->getNome();


        $isEdit = $acl->isAllowed($user->getRole()->getNome(), 'Medida::Medida', "Editar");
              $acl_result = $acl->isAllowed($role, $module . '::' . $controller, $action);

        ?>
        <div class="panel-body" style="padding-top: 0;">

            <table class="table">
                <tr>
                    <th>ID</th>

                    <th class="text-capitalize col-md-1">Oficio</th>
                    <th class=""">Nome</th>
                    <th class="">Acusado</th>
                    <th class="">Data</th>
                    <th class="">Tel.Res.</th>
                    <th class="">Tel.Cel.</th>
                    <th class="">Estado</th>
                    <th class=""">Cidade</th>
                    <th class=""   ">Bairro</th>
                    <th >Endereço</th>
                    <?php
                      if ($isEdit) { ?>
                        <th>Ação</th>
                    <?php  } ?>
                </tr>
                <?php foreach ($this->data as $entity): ?>
                    <tr>
                        <td><?php echo $entity->getId(); ?></td>

                        <td><?php echo $entity->getOficio(); ?></td>
                        <td><?php echo $entity->getNome(); ?></td>
                        <td><?php echo $entity->getAcusado(); ?></td>
                        <td> <?php echo $entity->getData()->format('d/m/Y'); ?></td>
                        <td><?php echo $entity->getTelr(); ?></td>
                        <td><?php echo $entity->getTelc(); ?></td>
                        <td><?php echo $entity->getEstado(); ?></td>
                        <td><?php echo $entity->getCidade(); ?></td>
                        <td><?php echo $entity->getBairro(); ?></td>
                        <td><?php echo $entity->getRua(); ?></td>

                        <td>
                        <a href="<?php echo $this->url('medida/default',
                            array('controller' => 'medida', 'action' => 'baixar_doc', 'id' => $entity->getId())); ?>"><i
                                class=" glyphicon glyphicon-save"></i></a>

                        <?php if ($this->auth->hasIdentity() && $isEdit) { ?>

                                <a href="<?php echo $this->url('medida/default',
                                    array('controller' => 'medida', 'action' => 'editar', 'id' => $entity->getId())); ?>"><i
                                        class="glyphicon glyphicon-edit text-success"></i></a>
                                <a href="<?php echo $this->url('medida/default',
                                    array('controller' => 'medida', 'action' => 'remover', 'id' => $entity->getId())); ?>"><i
                                        class="glyphicon glyphicon-trash text-danger"></i></a>
                            </td>
                        <?php } ?>
                    </tr>
                <?php endforeach; ?>

            </table>
        </div>
        <div class="panel-footer">
            <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
        </div>

    </div>
</div>
