<?php
/**
 * Created by PhpStorm.
 * User: walmirlsj
 * Date: 16/07/15
 * Time: 23:56
 */
?>
<?php
/*?>
<div id="modal-actions" class="modal fade" id="delete-label-modal" tabindex="-1" role="dialog" aria-labelledby="delete-label-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="delete-label-modal-label"><?php echo $this->escapeHtml($title); ?></h4>
</div>
<div class="modal-body">
    Are you sure that you want to delete
<!--    '--><?php //echo $this->escapeHtml($label->getName()); ?><!--'?-->
</div>

<?php
//$url = $this->url('label', array(
//    'action' => 'delete',
//    'id' => $label->getId(),
//));
?>
<div class="modal-footer">
    <form action="<?php //echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php //echo (int) $label->getId(); ?>" />
            <input type="submit" class="btn btn-primary" name="delete" value="Yes" />
            <input type="submit" class="btn btn-default" name="delete" value="No" />
        </div>
    </form>
</div>
</div>
</div>
</div>