<?php
$urlPattern = strtok($_SERVER["REQUEST_URI"], '?');
$query = $_SERVER["QUERY_STRING"] ? '?' . $_SERVER["QUERY_STRING"] : '';
$formatUrl = function ($page) use ($urlPattern, $query) {

    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . '/page/' . (int)$page .$query;

    else
        return preg_replace('@/page/\d+@', '/page/' . (int)$page .$query, $urlPattern);
};


if ($this->pageCount):
    ?>

    <div class="pagination-centered" style="margin: 0px;">

        <ul class="pagination">

            <?php if (isset($this->previous)): ?>

                <li><a href="<?php echo $formatUrl($this->previous); ?>">«</a></li>

            <?php else: ?>

                <li class="disabled"><a href="#">«</a></li>

            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>

                    <li>

                        <a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>

                    </li>

                <?php else: ?>

                    <li class="active">

                        <a href="#"><?php echo $page; ?></a>

                    </li>

                <?php endif; ?>

            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>

                <li><a href="<?php echo $formatUrl($this->next); ?>">»</a></li>

            <?php else: ?>

                <li class="disabled"><a href="#">»</a></li>

            <?php endif; ?>

        </ul>

    </div>
<?php endif; ?>