<?php

$entity = $this->entity;
//
//if($this->entity===null)
//    echo 'null';
//else
//    echo 'ok';

if (NULL !== $this->entity) {
    ?>
    <div class="col-lg-12">

        <div class="panel panel-crud-dark">
            <div class="panel-heading">
                <div class="panel-title">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <span class="h3">
                        <b>
                            <?php
                            echo $entity->getMarca()->getDescricao() . ' ' . $entity->getModelo() . ' ' . $entity->getVersao();
                            //getMarca()->getDescricao()
                            ?>
                        </b>
                    </span>
                </div>
            </div>
            <?php
            $path_images = './public';
            $path_user = $entity->getPath();
            $path_full = $path_images . $path_user;
            $diretorio = dir($path_full);

            //            echo "Lista de Arquivos do diretório '<strong>" . $path_full . "</strong>':<br />";;
            //    if (!file_exists($path))
            $images = array();
            $i = 0;
            while ($arquivo = $diretorio->read()) {
                if (substr($arquivo, strlen($arquivo) - 4, 4) == '.jpg') {
                    $images = array_merge($images, array($i => $path_user . $arquivo));
                    $i++;
                }
            }
            $diretorio->close();
            //            var_dump($images);
            //            exit;
            ?>
            <div class="panel-body">
                <div class="col-md-8 clearfix" style="margin-bottom: 5px;">

                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <!--                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>-->
                            <!--                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>-->
                            <!--                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>-->
                            <?php $i = 0;
                            foreach ($images as $src) {
                                ?>
                                <li data-target="#carousel-example-generic" data-slide-to="<?php echo $i;
                                $i++; ?>"></li>
                            <?php } ?>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <?php $i = 0;
                            foreach ($images as $src) {
                                ?>
                                <div class="item <?php echo $i == 0 ? 'active' : ''; ?>">
                                    <img src=" <?php echo $src; ?>" alt="..."
                                         style="width:100% !important;height:auto !important;max-width: 100% !important;">

                                    <div class="carousel-caption">
                                        ...
                                    </div>
                                </div>

                                <?php $i++; ?>
                            <?php } ?>

                            <!--                            <div class="item active">-->
                            <!--                                <img src="/img/cars/c4.jpg" alt="..."-->
                            <!--                                     style="width:100% !important;height:auto !important;max-width: 100% !important;">-->
                            <!---->
                            <!--                                <div class="carousel-caption">-->
                            <!--                                    ...-->
                            <!--                                </div>-->
                            <!--                            </div>-->
                            <!--                            <div class="item">-->
                            <!--                                <img src="/img/cars/c5.jpg" alt="..."-->
                            <!--                                     style="width:100% !important;height:auto !important;max-width: 100% !important;">-->
                            <!---->
                            <!--                                <div class="carousel-caption">-->
                            <!--                                    ...-->
                            <!--                                </div>-->
                            <!--                            </div>-->
                            <!--                            <div class="item">-->
                            <!--                                <img src="/img/cars/c8.jpg" alt="..."-->
                            <!--                                     style="width:100% !important;height:auto !important;max-width: 100% !important;">-->
                            <!---->
                            <!--                                <div class="carousel-caption">-->
                            <!--                                    ...-->
                            <!--                                </div>-->
                            <!--                            </div>-->
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button"
                           data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button"
                           data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>

                </div>

                <div class="col-md-4 clearfix">
                    <div class="panel panel-crud-gray">
                        <div class="panel-heading">
                            <span class="h2 clearfix">Sobre o veiculo</span>
                        </div>
                        <div class="panel-body text-left">
                            <dl>
                                <dd>
                                    <span class="legend">Marca: </span><span
                                        class="value"><?php echo $entity->getMarca()->getDescricao(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Modelo: </span><span
                                        class="value"><?php echo $entity->getModelo(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Versão: </span><span
                                        class="value"><?php echo $entity->getVersao(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Ano/modelo: </span><span
                                        class="value"><?php echo $entity->getAnoModelo() ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Cor: </span><span
                                        class="value"><?php echo $entity->getCor(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Km: </span><span
                                        class="value"><?php echo $entity->getKm(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Portas: </span><span
                                        class="value"><?php echo $entity->getPortas(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Direção: </span><span
                                        class="value"><?php echo $entity->getDirecao(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Transmissão: </span><span
                                        class="value"><?php echo $entity->getTransmissao(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Opcionais: </span><span
                                        class="value"><?php echo $entity->getOpcionais(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Observação: </span><span class="value">
                                        <?php echo $entity->getObs(); ?>
                                    </span>
                                </dd>
                                <dd>
                                    <span class="legend">Preço: R$ </span><span
                                        class="value"><?php echo $entity->getPrice(); ?></span>
                                </dd>
                                <dd>
                                    <span class="legend">Vendido? </span><span
                                        class="value"><?php echo $entity->isStocked() ? 'Sim' : 'Não'; ?></span>
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>


<?php } else { ?>

    <div class="jumbotron">
        <h1>Ops.!</h1>

        <p>Veiculo não encontrado.</p>
        <!--        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>-->
    </div>

<?php } ?>