<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('M ' . $this->translate('Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body style="background-color: #E7E7E7/*#262626*/;">
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('img/logo-tavel.png') ?>"
                     alt="Zend Framework 2"/><?php echo $this->translate('') ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Index') ?></a></li>
                <li class=""><a
                        href="<?php echo $this->url('catalogo') ?>"><?php echo $this->translate('Catalogo') ?></a></li>
                <li class=""><a
                        href="<?php echo $this->url('catalogo/list', array('controller' => 'listar', 'action' => 'listar', 'categoria' => 'veiculo', 'refid' => '1')) ?>"><?php echo $this->translate('Catalogo 1') ?></a>
                </li>
                <li class=""><a
                        href="<?php echo $this->url('catalogo/list', array('controller' => 'listar', 'action' => 'detalhe', 'categoria' => 'veiculo', 'refid' => '1')) ?>"><?php echo $this->translate('Catalogo 1') ?></a>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
