<?php
/**
 * Created by PhpStorm.
 * User: walmirlsj
 * Date: 04/07/15
 * Time: 13:02
 */
?>

<div class="panel panel-primary">
    <div class="panel-body">
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span>Noticias</span>
                </div>
                <div class="panel-body" style="padding:0;margin: 0;">
                    <?php echo $this->signinBlock; ?>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span>Eventos</span>
                </div>
                <div class="panel-body" style="padding:0;margin: 0;">
                    <?php echo $this->signupBlock; ?>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span>Lançamentos</span>
                </div>
                <div class="panel-body" style="padding:0;margin: 0;">
                    <?php echo $this->signinBlock; ?>
                </div>
            </div>
        </div>

    </div>
</div>

